name: leetcode-solved-problem-tracker
uses: nurgasemetey/leetcode-solved-problem-tracker@v1.6


on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * *' # according to UTC

jobs:
  leetcode_solved_problem_tracker:
    runs-on: ubuntu-latest
    name: Save each day's solved problem counts
    steps:
      - uses: actions/checkout@v2
      - name: leetcode-solved-problem-tracker step
        id: hello
        uses: nurgasemetey/leetcode-solved-problem-tracker@v1.6
        with:
          username: ${{ secrets.LEETCODE_USERNAME }} # if you want to hide your username
          github-token: ${{ secrets.GITHUB_TOKEN }} # no need to generate token, it is generated automatically when you use action
